name: Compile and release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: echo SCRIPTS_PATH=./addons/sourcemod >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./addons/sourcemod/scripting/towerdefense.sp

      - name: Compile plugins
        run: |
          mkdir ../plugins
          spcomp -w234 -O2 -v2 -i"include" -o"../plugins/towerdefense.smx" towerdefense.sp
          echo "===OUT FILES==="
          ls ../plugins
        working-directory: ${{ env.SCRIPTS_PATH }}/scripting

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -y -r towerdefense-${{ steps.changelog.outputs.version }}.zip configs plugins scripting extensions gamedata translations data
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: "${{ env.SCRIPTS_PATH }}/towerdefense-${{ steps.changelog.outputs.version }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
