name: Test Sourcemod compilation

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: echo SCRIPTS_PATH=./addons/sourcemod >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./addons/sourcemod/scripting/towerdefense.sp

      - name: Compile plugins
        run: |
          mkdir ../plugins
          spcomp -w234 -O2 -v2 -i"include" -o"../plugins/towerdefense.smx" towerdefense.sp
          echo "===OUT FILES==="
          ls ../plugins
        working-directory: ${{ env.SCRIPTS_PATH }}/scripting
